spring.application.name=CampingHub

# --- Configuracion de MySQL ---

# 1. Deshabilitar la consola H2
spring.h2.console.enabled=false

# 2. Credenciales de la Base de Datos (AJUSTAR ESTOS VALORES)
spring.datasource.url=jdbc:mysql://localhost:3306/campinghub_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=ADMIN
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# 3. Configuracion JPA/Hibernate para MySQL
# 'update' mantiene el esquema y actualiza las tablas (ideal para desarrollo)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect